DROP TABLE IF EXISTS delivery_history CASCADE;
DROP TABLE IF EXISTS delivery_product CASCADE;
DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS client CASCADE;

DROP TYPE IF EXISTS person_type_enum CASCADE;
DROP TYPE IF EXISTS delivery_status_enum CASCADE;

CREATE TYPE person_type_enum AS ENUM ('INDIVIDUAL', 'LEGAL_ENTITY');

CREATE TYPE delivery_status_enum AS ENUM (
    'PENDING',
    'IN_TRANSIT',
    'DELIVERED',
    'CANCELED',
    'NOT_PERFORMED'
);
