DROP TABLE IF EXISTS historico_entrega CASCADE;
DROP TABLE IF EXISTS entrega_produto CASCADE;
DROP TABLE IF EXISTS entrega CASCADE;
DROP TABLE IF EXISTS produto CASCADE;
DROP TABLE IF EXISTS endereco CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;

DROP TYPE IF EXISTS tipo_pessoa CASCADE;
DROP TYPE IF EXISTS status_entrega CASCADE;

CREATE TYPE tipo_pessoa AS ENUM ('PF', 'PJ');

CREATE TYPE status_entrega AS ENUM (
    'PENDENTE',
    'EM_TRANSITO',
    'ENTREGUE',
    'CANCELADA',
    'NAO_REALIZADA'
);
